/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diseño;

/**
 *
 * @author COMPUTER
 */
public class is_as_manager extends javax.swing.JFrame {

    /**
     * Creates new form is_as_manager
     */
    public is_as_manager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agregar_nuevo_empleado = new javax.swing.JPanel();
        TitEmp = new javax.swing.JLabel();
        apeynom = new javax.swing.JLabel();
        identi = new javax.swing.JLabel();
        apeynomaux = new javax.swing.JTextField();
        identiaux = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        modEmpleado = new javax.swing.JPanel();
        napeynom = new javax.swing.JLabel();
        midenti = new javax.swing.JLabel();
        apeaux = new javax.swing.JTextField();
        idaux = new javax.swing.JTextField();
        acectar = new javax.swing.JButton();
        TitVentana = new javax.swing.JLabel();
        Eliminar_empleado = new javax.swing.JPanel();
        E_eTitulo = new javax.swing.JLabel();
        elimemptext = new javax.swing.JTextField();
        elimEmpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitEmp.setFont(new java.awt.Font("Franklin Gothic Book", 0, 13)); // NOI18N
        TitEmp.setText("Agregar Nuevo Empleado:");

        apeynom.setText("Apellido y Nombre:");

        identi.setText("Identificador:");

        apeynomaux.setText("Ingrese apellido y nombre");

        identiaux.setText("Ingrese Identificador");
        identiaux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identiauxActionPerformed(evt);
            }
        });

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        modEmpleado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificar Empelado:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Book", 0, 13))); // NOI18N

        napeynom.setText("Nuevo Apellido y Nombre:");

        midenti.setText("Identificador del Empleado:");

        apeaux.setText("Ingrese apellido y nombre");

        idaux.setText("Ingrese el id. anterior");

        acectar.setText("Aceptar");

        javax.swing.GroupLayout modEmpleadoLayout = new javax.swing.GroupLayout(modEmpleado);
        modEmpleado.setLayout(modEmpleadoLayout);
        modEmpleadoLayout.setHorizontalGroup(
            modEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(acectar)
                    .addGroup(modEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(modEmpleadoLayout.createSequentialGroup()
                            .addComponent(napeynom, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(apeaux, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(modEmpleadoLayout.createSequentialGroup()
                            .addComponent(midenti)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(idaux))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        modEmpleadoLayout.setVerticalGroup(
            modEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(napeynom)
                    .addComponent(apeaux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(modEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(midenti)
                    .addComponent(idaux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(acectar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Agregar_nuevo_empleadoLayout = new javax.swing.GroupLayout(Agregar_nuevo_empleado);
        Agregar_nuevo_empleado.setLayout(Agregar_nuevo_empleadoLayout);
        Agregar_nuevo_empleadoLayout.setHorizontalGroup(
            Agregar_nuevo_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agregar_nuevo_empleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Agregar_nuevo_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitEmp)
                    .addGroup(Agregar_nuevo_empleadoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(Agregar_nuevo_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(aceptar)
                            .addGroup(Agregar_nuevo_empleadoLayout.createSequentialGroup()
                                .addGroup(Agregar_nuevo_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(apeynom)
                                    .addComponent(identi, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addGroup(Agregar_nuevo_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(identiaux)
                                    .addComponent(apeynomaux, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(modEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Agregar_nuevo_empleadoLayout.setVerticalGroup(
            Agregar_nuevo_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agregar_nuevo_empleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Agregar_nuevo_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apeynom)
                    .addComponent(apeynomaux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(Agregar_nuevo_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identiaux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aceptar)
                .addGap(18, 18, 18)
                .addComponent(modEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TitVentana.setFont(new java.awt.Font("Franklin Gothic Book", 1, 13)); // NOI18N
        TitVentana.setText("Control de Empleados");

        Eliminar_empleado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eliminar Empleado:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Book", 0, 13))); // NOI18N

        E_eTitulo.setText("Ingrese el id del empleado a eliminar:");

        elimemptext.setText("Ingrese Identificador");
        elimemptext.setPreferredSize(new java.awt.Dimension(155, 22));

        elimEmpButton.setText("Aceptar");

        javax.swing.GroupLayout Eliminar_empleadoLayout = new javax.swing.GroupLayout(Eliminar_empleado);
        Eliminar_empleado.setLayout(Eliminar_empleadoLayout);
        Eliminar_empleadoLayout.setHorizontalGroup(
            Eliminar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Eliminar_empleadoLayout.createSequentialGroup()
                .addGroup(Eliminar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Eliminar_empleadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(E_eTitulo))
                    .addGroup(Eliminar_empleadoLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(Eliminar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(elimEmpButton)
                            .addComponent(elimemptext, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        Eliminar_empleadoLayout.setVerticalGroup(
            Eliminar_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Eliminar_empleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(E_eTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(elimemptext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(elimEmpButton)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Agregar_nuevo_empleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TitVentana)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Eliminar_empleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitVentana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Agregar_nuevo_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Eliminar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void identiauxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identiauxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identiauxActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(is_as_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(is_as_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(is_as_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(is_as_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new is_as_manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Agregar_nuevo_empleado;
    private javax.swing.JLabel E_eTitulo;
    private javax.swing.JPanel Eliminar_empleado;
    private javax.swing.JLabel TitEmp;
    private javax.swing.JLabel TitVentana;
    private javax.swing.JButton acectar;
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField apeaux;
    private javax.swing.JLabel apeynom;
    private javax.swing.JTextField apeynomaux;
    private javax.swing.JButton elimEmpButton;
    private javax.swing.JTextField elimemptext;
    private javax.swing.JTextField idaux;
    private javax.swing.JLabel identi;
    private javax.swing.JTextField identiaux;
    private javax.swing.JLabel midenti;
    private javax.swing.JPanel modEmpleado;
    private javax.swing.JLabel napeynom;
    // End of variables declaration//GEN-END:variables
}
