/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diseño;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author COMPUTER
 */

public class Sistema_de_Control extends javax.swing.JFrame {    
    /**
     * Creates new form Sistema_de_Control
     */
    
    
    public Sistema_de_Control() {
        initComponents();
        
        //Centramos la ubicación de la ventana con respecto a la pantalla        
        setLocationRelativeTo(null);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoaccproductor = new javax.swing.ButtonGroup();
        grupoconsuprodu = new javax.swing.ButtonGroup();
        grupoaccestable = new javax.swing.ButtonGroup();
        grupoconsuestable = new javax.swing.ButtonGroup();
        grupoaccitambo = new javax.swing.ButtonGroup();
        grupo_consu_tambo = new javax.swing.ButtonGroup();
        grupo_acc_animal = new javax.swing.ButtonGroup();
        grupo_consu_animal = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttaltaprodu = new javax.swing.JRadioButton();
        buttmodprodu = new javax.swing.JRadioButton();
        buttelimprodu = new javax.swing.JRadioButton();
        JB_Prod_Aceptar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        JRB_Prod_Pertenencia = new javax.swing.JRadioButton();
        JRB_Prod_Telefono = new javax.swing.JRadioButton();
        JRB_Estab_ACargo = new javax.swing.JRadioButton();
        JRB_Prod_ListarProductores = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JRB_AgregarEstablecimiento = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        JB_Estab_Aceptar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        JB_Tambo_Aceptar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JRB_AGREGARANIMAL = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        JB_Animal_Aceptar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        JB_Produccion_CargarNuevo = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione la opción que desee realizar:");

        grupoaccproductor.add(buttaltaprodu);
        buttaltaprodu.setText("Agregar nuevo productor.");
        buttaltaprodu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttaltaproduActionPerformed(evt);
            }
        });

        grupoaccproductor.add(buttmodprodu);
        buttmodprodu.setText("Modificar productor existente.");

        grupoaccproductor.add(buttelimprodu);
        buttelimprodu.setText("Eliminar productor.");

        JB_Prod_Aceptar.setText("Aceptar");
        JB_Prod_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Prod_AceptarActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleccione la consulta a realizar:");

        grupoaccproductor.add(JRB_Prod_Pertenencia);
        JRB_Prod_Pertenencia.setText("Pertenecia.");
        JRB_Prod_Pertenencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_Prod_PertenenciaActionPerformed(evt);
            }
        });

        grupoaccproductor.add(JRB_Prod_Telefono);
        JRB_Prod_Telefono.setText("Número de teléfono.");
        JRB_Prod_Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_Prod_TelefonoActionPerformed(evt);
            }
        });

        grupoaccproductor.add(JRB_Estab_ACargo);
        JRB_Estab_ACargo.setText("Establecimientos a cargo.");

        grupoaccproductor.add(JRB_Prod_ListarProductores);
        JRB_Prod_ListarProductores.setText("Listar productores.");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttmodprodu)
                            .addComponent(buttaltaprodu)
                            .addComponent(buttelimprodu))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JRB_Prod_Pertenencia)
                    .addComponent(JRB_Prod_Telefono)
                    .addComponent(JRB_Estab_ACargo)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JB_Prod_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JRB_Prod_ListarProductores))
                    .addComponent(jLabel2))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(JRB_Prod_Pertenencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JRB_Prod_Telefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JRB_Estab_ACargo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JRB_Prod_ListarProductores))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(buttaltaprodu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttmodprodu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttelimprodu)))
                .addGap(63, 63, 63)
                .addComponent(JB_Prod_Aceptar)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Productores", jPanel6);

        jLabel3.setText("Seleccione la opción que desea realizar:");

        grupoaccestable.add(JRB_AgregarEstablecimiento);
        JRB_AgregarEstablecimiento.setText("Agregar nuevo establecimiento.");

        grupoaccestable.add(jRadioButton5);
        jRadioButton5.setText("Modificar establecimiento existente.");

        grupoaccestable.add(jRadioButton6);
        jRadioButton6.setText("Eliminar establecimiento.");

        JB_Estab_Aceptar.setText("Aceptar");
        JB_Estab_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Estab_AceptarActionPerformed(evt);
            }
        });

        jLabel4.setText("Seleccione la consulta a realizar:");

        grupoaccestable.add(jRadioButton7);
        jRadioButton7.setText("Pertenencia.");

        grupoaccestable.add(jRadioButton9);
        jRadioButton9.setText("Productor al que pertenece.");

        grupoaccestable.add(jRadioButton10);
        jRadioButton10.setText("Nombre.");

        grupoaccestable.add(jRadioButton11);
        jRadioButton11.setText("Ubicanción.");

        grupoaccestable.add(jRadioButton12);
        jRadioButton12.setText("Teléfono.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton5)
                            .addComponent(JRB_AgregarEstablecimiento)
                            .addComponent(jRadioButton6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3)))
                .addGap(154, 154, 154)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_Estab_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton12))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JRB_AgregarEstablecimiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton7)
                        .addGap(5, 5, 5)
                        .addComponent(jRadioButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton12)
                .addGap(39, 39, 39)
                .addComponent(JB_Estab_Aceptar)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Establecimiento", jPanel1);

        jLabel5.setText("Seleccione la opción que desea realizar:");

        jLabel6.setText("Seleccione la consulta a realizar:");

        grupoaccitambo.add(jRadioButton8);
        jRadioButton8.setText("Agregar nuevo tambo.");

        grupoaccitambo.add(jRadioButton13);
        jRadioButton13.setText("Modificar tambo existente.");

        grupoaccitambo.add(jRadioButton14);
        jRadioButton14.setText("Eliminar tambo.");

        grupoaccitambo.add(jRadioButton15);
        jRadioButton15.setText("Establecimiento al que pertence.");

        grupoaccitambo.add(jRadioButton16);
        jRadioButton16.setText("Nombre.");

        grupoaccitambo.add(jRadioButton17);
        jRadioButton17.setText("Distribución.");
        jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton17ActionPerformed(evt);
            }
        });

        grupoaccitambo.add(jRadioButton18);
        jRadioButton18.setText("Cantidad de animales.");

        JB_Tambo_Aceptar.setText("Aceptar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton13)
                            .addComponent(jRadioButton8)
                            .addComponent(jRadioButton14))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton16)
                            .addComponent(jRadioButton15)
                            .addComponent(jRadioButton17)
                            .addComponent(jRadioButton18)
                            .addComponent(JB_Tambo_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton18)
                .addGap(34, 34, 34)
                .addComponent(JB_Tambo_Aceptar)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tambo", jPanel2);

        jLabel7.setText("Seleccione una opción a realizar:");

        jLabel8.setText("Seleccione una opcion a consultar:");

        grupo_acc_animal.add(JRB_AGREGARANIMAL);
        JRB_AGREGARANIMAL.setText("Agregar nuevo animal.");

        grupo_acc_animal.add(jRadioButton21);
        jRadioButton21.setText("Modificar datos animal.");

        grupo_acc_animal.add(jRadioButton22);
        jRadioButton22.setText("Eliminar animal.");

        grupo_acc_animal.add(jRadioButton23);
        jRadioButton23.setText("Obtener raza.");

        grupo_acc_animal.add(jRadioButton24);
        jRadioButton24.setText("Obtener etiqueta.");

        JB_Animal_Aceptar.setText("Aceptar");
        JB_Animal_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Animal_AceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JRB_AGREGARANIMAL)
                            .addComponent(jRadioButton21)
                            .addComponent(jRadioButton22))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jRadioButton24)
                                .addComponent(jRadioButton23, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(JB_Animal_Aceptar))))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton24))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(JRB_AGREGARANIMAL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton22)))
                .addGap(51, 51, 51)
                .addComponent(JB_Animal_Aceptar)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Animal", jPanel3);

        jLabel9.setText("Para cargar la producción: ");

        JB_Produccion_CargarNuevo.setText("Cargar nuevo");
        JB_Produccion_CargarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Produccion_CargarNuevoActionPerformed(evt);
            }
        });

        jLabel16.setText("Para consultar la  produción:");

        jButton1.setText("Consultar Producción");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JB_Produccion_CargarNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(190, 190, 190)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(326, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel16))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Produccion_CargarNuevo)
                    .addComponent(jButton1))
                .addGap(242, 242, 242))
        );

        jTabbedPane1.addTab("Producción", jPanel4);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttaltaproduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttaltaproduActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_buttaltaproduActionPerformed

    private void JRB_Prod_PertenenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_Prod_PertenenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRB_Prod_PertenenciaActionPerformed

    private void JRB_Prod_TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_Prod_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRB_Prod_TelefonoActionPerformed

    private void jRadioButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton17ActionPerformed

    private void JB_Produccion_CargarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Produccion_CargarNuevoActionPerformed
        // TODO add your handling code here:
        cargarProducción c = new cargarProducción();
        
        c.setVisible(true);
    }//GEN-LAST:event_JB_Produccion_CargarNuevoActionPerformed

    private void JB_Estab_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Estab_AceptarActionPerformed
        // TODO add your handling code here:
        
        if (JRB_AgregarEstablecimiento.isSelected()) {
            // Ejecutar la Ventana AltaEstablecimiento
            altaEstablecimiento altaEs = new altaEstablecimiento();
            altaEs.setTitle("Alta de nuevo establecimiento");
            altaEs.setVisible(true);
        }
        
    }//GEN-LAST:event_JB_Estab_AceptarActionPerformed

    private void JB_Prod_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Prod_AceptarActionPerformed
        // TODO add your handling code here:
        
        if (buttaltaprodu.isSelected()) {
            altaProductor ap=new altaProductor();
            ap.setTitle("Alta de nuevo productor");
            ap.setLocationRelativeTo(null);
            ap.setVisible(true);
        }
        
        if (JRB_Prod_ListarProductores.isSelected()) {
            Consultar_productores cp = new Consultar_productores();
            cp.setTitle("Consultar productores");
            cp.setLocationRelativeTo(null);
            cp.setVisible(true);
        }
    }//GEN-LAST:event_JB_Prod_AceptarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        consultarProducción c = new consultarProducción();
        c.setTitle("Consultar producción");
        c.setLocationRelativeTo(null);
        c.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JB_Animal_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Animal_AceptarActionPerformed
        // TODO add your handling code here:
        if (JRB_AGREGARANIMAL.isSelected()) {
            altaAnimal a = new altaAnimal();
            a.setTitle("Alta de nuevo Animal");
            a.setLocationRelativeTo(null);
            a.setVisible(true);
        }
    }//GEN-LAST:event_JB_Animal_AceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema_de_Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema_de_Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema_de_Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema_de_Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema_de_Control().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Animal_Aceptar;
    private javax.swing.JButton JB_Estab_Aceptar;
    private javax.swing.JButton JB_Prod_Aceptar;
    private javax.swing.JButton JB_Produccion_CargarNuevo;
    private javax.swing.JButton JB_Tambo_Aceptar;
    private javax.swing.JRadioButton JRB_AGREGARANIMAL;
    private javax.swing.JRadioButton JRB_AgregarEstablecimiento;
    private javax.swing.JRadioButton JRB_Estab_ACargo;
    private javax.swing.JRadioButton JRB_Prod_ListarProductores;
    private javax.swing.JRadioButton JRB_Prod_Pertenencia;
    private javax.swing.JRadioButton JRB_Prod_Telefono;
    private javax.swing.JRadioButton buttaltaprodu;
    private javax.swing.JRadioButton buttelimprodu;
    private javax.swing.JRadioButton buttmodprodu;
    private javax.swing.ButtonGroup grupo_acc_animal;
    private javax.swing.ButtonGroup grupo_consu_animal;
    private javax.swing.ButtonGroup grupo_consu_tambo;
    private javax.swing.ButtonGroup grupoaccestable;
    private javax.swing.ButtonGroup grupoaccitambo;
    private javax.swing.ButtonGroup grupoaccproductor;
    private javax.swing.ButtonGroup grupoconsuestable;
    private javax.swing.ButtonGroup grupoconsuprodu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
